name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-qemu-action@v1

    - name: Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Docker login, Build and push image
      env:
        DOCKER_TLS_CERTDIR: "/certs"
      run: |
        echo $REGISTRY_PASS | docker login -u ${{ secrets.REGISTRY_USER }} --password-stdin
        docker build -t carlosfalcone/app-cicd-dio:1.0 app/.
        docker push carlosfalcone/app-cicd-dio:1.0
