name: Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Test SSH Connection and Run Code
        run: |
          echo -n "${{ secrets.SSH_KEY }}" > key.pem
          chmod 400 key.pem
          ssh -o StrictHostKeyChecking=no -T -i key.pem gcp@${{ secrets.SSH_SERVER }}
          sudo rm -Rf ./app-cicd-dio2/
          sudo git clone https://github.com/carlosfalcone/app-cicd-dio2.git
          echo "clone finalizado"
          echo "Current working directory: $(pwd)"

        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_SERVER: ${{ secrets.SSH_SERVER }}
