name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-qemu-action@v1

    - name: Docker Login
      run: echo "${{ secrets.REGISTRY_PASS }}" | docker login -u "${{ secrets.REGISTRY_USER }}" --password-stdin

    - name: Docker build and push
      env:
        DOCKER_TLS_CERTDIR: "/certs"
      run: |
        docker build -t carlosfalcone/app-cicd-dio:1.0 ./app/.
        docker push carlosfalcone/app-cicd-dio:1.0

  deploy_gcp:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Deploy to GCP
      run: |
        cd /
        sudo git clone https://github.com/carlosfalcone/app-cicd-dio2.git

        